title: 'Benzlim Documentation'
default_lang: en
author:
  name: 'Amin Akbari'
  email: aminakbari@live.com
taxonomies:
  - category
  - tag
metadata:
  description: 'The official documentation for Benzlim, a Python powered fuel price prediction software.'
  theme-color: ffffff
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
